system:
    site:
        field_templates:
            - {template: 'AppBundle::ezpoll_view.html.twig', priority: 0}

    admin_group:
        field_templates:
            - { template: 'AppBundle:platformui/field:ezpoll_view.html.twig', priority: 10 }

        fielddefinition_settings_templates:
            - {template: AppBundle:platformui/content_type/view:ezpoll.html.twig, priority: 0}

        fielddefinition_edit_templates:
            - {template: AppBundle:platformui/content_type/edit:ezpoll.html.twig, priority: 0}
