ezpublish:
    system:
        site:
            field_templates:
                - { template: AppBundle::ezpoll_view.html.twig, priority: 0}

        admin_group:
            field_templates:
                - { template: AppBundle:adminui/field:ezpoll_view.html.twig, priority: 10 }

            fielddefinition_settings_templates:
                - { template: AppBundle:adminui/content_type/view:ezpoll.html.twig, priority: 0}

            fielddefinition_edit_templates:
                - { template: AppBundle:adminui/content_type/edit:ezpoll.html.twig, priority: 0}

            limitation_value_templates:
                - { template: AppBundle:Limitation:question_limitation_value.html.twig, priority: 0 }

twig:
    form_themes:
          - AppBundle:adminui/field:ezpoll_edit.html.twig
