services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\Component\TwigComponent:
        arguments:
            $template: 'AppBundle:adminui/component:ezpoll_edit_js.html.twig'
            $parameters: []
        tags:
            - { name: ezplatform.admin_ui.component, group: 'content-edit-form-after' }
            - { name: ezplatform.admin_ui.component, group: 'content-create-form-after' }

    EzSystems\EzPlatformAdminUi\Component\LinkComponent:
        arguments:
            $href: '/bundles/app/css/style.css'
        tags:
            - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }
